### ISSUE TITLE
Should students have a first name and a last name?

### ISSUE THREAD

**Issue by DamienFlury** [DamienFlury/echoes#1]
# Question
Currently, students are authenticated using an email address. Should we implement a first name and a last name? If so, should we also authenticate via those credentials or stay with the email?
# Suggestion
I suggest we keep authenticating via email, but require users to provide their first and last name when they create an account.

**Comment by TheCakegamer** [comment]
Good sugestion:

Sign in with email, firstname, lastname and password
Login with email and password
